##===- projects/new_project/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=profdb setprof edgeprof runtime instrument addrprof
# spec_opts feedback disabled

# Required for using boost::lexical_cast
REQUIRES_RTTI = 1

include $(LEVEL)/Makefile.common
