##===- projects/new_project/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
SOURCES=

LIBRARYNAME=DDPInstrument

#LOADABLE_MODULE = 1
BUILD_ARCHIVE=1

include $(LEVEL)/Makefile.common
